# Generated by Django 4.1 on 2022-08-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('brend', models.CharField(max_length=40)),
                ('kelgan_narx', models.IntegerField()),
                ('sotuv_narx', models.IntegerField()),
                ('miqdor', models.IntegerField()),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokon', models.CharField(max_length=50)),
                ('ism', models.CharField(max_length=40)),
                ('telefon', models.IntegerField()),
                ('manzil', models.CharField(max_length=40)),
                ('qarz', models.IntegerField(default=0)),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.ombor')),
            ],
        ),
    ]
